---
- hosts: speedment
  become: True

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build

  roles:
  - role: postgresql
    download_directory: "~/"