# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "database" do |database|
    database.vm.box = "ubuntu/trusty64"
    database.vm.network "private_network", ip: "10.1.1.10"
    database.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "2048"]
    end

  end

  config.vm.provision "ansible_local" do |prov|
    prov.install = true
    prov.playbook = "/vagrant/ansible/database.yml"
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  end

end
